Added new changes to navbar, sections and scrollbar
Multitec-UA/MultiWeb pull request #5
Opened 2022-10-26 21:02 UTC by m-Thelinn

About section completed
Added white color to navbar
Added new MT logo to navbar
Added new scrollbar style
Some translations in various sections

2022-10-27 05:55 UTC, sergioconv approved these changes

2022-10-27 17:55 UTC, MCheca requested changes
Revisa los comentarios

2022-10-27 17:55 UTC, MCheca commented on assets/css/style.css
> +#scrollPath {
Si no se usa bórralo

2022-10-27 17:55 UTC, MCheca commented on assets/js/script.js
> +//SCROLLBAR
Si no se usa bórralo

2022-10-27 17:55 UTC, MCheca commented on src/index.html
> +                <!--<div id="progressbar"></div>
No dejes cosas comentadas que no se usan

2022-10-30 22:09 UTC, MCheca approved these changes
All is ok!!

2022-10-30 22:10 UTC, merged